name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          issue-message: "👋 Welcome to the repo, @${{ github.actor }}! Thanks for opening your first issue 🎉 Our team will review it soon. Feel free to explore and contribute more!"

          pr-message: "🚀 Hey @${{ github.actor }}! Thanks for your first pull request 🎉 We appreciate your contribution. A maintainer will review it shortly."
